### PR TITLE
Feat: update for v8

### PR DESCRIPTION
**Pull request by Zyie**
This PR updates the playground to work with v8 by default

I also fixed the issue where you couldn't select versions older than v8 because we released so many and the previous API request only grab the first 10 or so

### CODE REVIEW

**Review by bigtimebuddy — APPROVED** [review]

**Comment by englercj** [comment]
It has been a while since I've been in the world of Pixi.js! Thanks for this PR!

**Comment by englercj** [comment]
Having some trouble deploying. Looks like this stuff is so old none of it works with modern node versions. Will need to do some upgrading and fixing after work before I can deploy. Will get it done today though.

**Comment by englercj** [comment]
This is actually more work than I thought, won't get it done tonight. Should have some free time this weekend though to throw at it.

**Comment by englercj** [comment]
Finally got all the dependencies updated, updated to use async-await, updated the servers to latest OS, and updated node to v20 LTS. Phew! This has been deployed now, thanks again for the PR.

**Pull request merged**
